language: go
go:
- "1.12.x"
branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/ # release tags, e.g. "1.2.3-abc"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
services:
- postgresql
- docker
addons:
  postgresql: "11.2"
jobs:
  include:
  - name: golint
    before_script:
    - go get golang.org/x/lint/golint
    script:
    - golint -set_exit_status pkg/... cmd/...
  - name: tests
    before_script:
    - createdb ulms-test -U postgres
    - go get github.com/golang/dep/cmd/dep
    - dep ensure -v
    script:
    - go test -v ./...
