[authn."iam.internal"]
audience = ["internal"]
key = "configs/com.example.iam.key"
trusted = true

[authn."iam.example.com"]
audience = ["example.com"]
key = "configs/com.example.iam.key"

[authz."example.com"]
uri = "https://example.com/auth"
token = "secret-token"
service_id = "ulms.service"
