db:
  driver: pgx
  # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
  source: dbname=ulms sslmode=disable user=postgres
  max-open-conns: 300
  max-idle-conns: 300

auth: configs/auth.toml

cors:
  allowed_hosts:
    - "*"
  max_age: 600

# https://docs.sentry.io/platforms/go/config/
sentry: {}
